# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: atlas_core writes things
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  linux user plays around with technology and writes
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://atlasc0r3.github.io" # the base hostname & protocol for your site, e.g. http://example.com
mastodon_username: atlas_core@linuxrocks.online
github_username:  AtlasC0R3

# Build settings
remote_theme: "bitbrain/jekyll-dash"
plugins:
  - jekyll-feed

# jekyll-paginate
paginate: 15
paginate_path: "/blog/page:num/"

dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"

  # the animation speed of the post scroll-in effect
  animation_speed: 50

  # wether to enable Right-to-Left support or not
  rtl: false

  # Replaces the default avatar provider (gravatar)
  avatar_source: github
  github_username: AtlasC0R3
  #avatar_source: local
  #avatar_path: /images/avatar.png

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://https://linuxrocks.online/@atlas_core
      icon: mastodon
      color: cyan
    - url: https://github.com/AtlasC0R3
      icon: github-square
      color: purple

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .vscode/
